### ISSUE TITLE
"Hello, I am very interested in this project. May I ask when the pre-trained model will be released?"

### ISSUE THREAD

**Issue by Haoo906** [sjtuplayer/Compositional_Neural_Painter#1]
"Hello, I am very interested in this project. May I ask when the pre-trained model will be released?"

**Comment by jinyizhang184** [comment]
Thank you for your attention. The author is attending ICCV in Paris right now, he will work on it as soon as possible.

**Comment by xiaolu7521** [comment]
Hello, the stroke renderer training code provided does not include the thinplatespline module?

**Comment by sjtuplayer** [comment]
Thanks for your attention to our work. I will release the checkpoints and testing code this weekend. But since I'm quite bussy before CVPR and I have not prepared them so well, there may be some problem when you run it. So, if you encounter any problem, please feel free to contact me.

**Comment by sjtuplayer** [comment]
Hi!~The models have been uploaded and the test code has been updated.

**Comment by Haoo906** [comment]
Thanks for sharing！In testing, I would like to generate higher-resolution oil painting images. If I only modify the size of the input image, canvas, and drawing boxes, will it achieve the desired result? I'm currently experimenting with this.

**Comment by sjtuplayer** [comment]
If you want to generate higher-resolution oil painting images. You have 2 choices:
1. you can just change the original size from 512 to the size you want in the functions named final_decode and oil_decoder.
2. To have a better result, you should also change the input size of the image from 512 to the size you want.
