### ISSUE TITLE
关于style transfer的问题

### ISSUE THREAD

**Issue by Donkdot** [sjtuplayer/Compositional_Neural_Painter#10]
你好！请问style transfer的方法该如何测试呢？

**Comment by sjtuplayer** [comment]
你好！style transfer的代码还在整理中。你也可以直接把重建的笔触作为初始化，使用论文中的风格损失+内容损失，以及DT.py中的DT loss优化笔触参数

**Comment by Donkdot** [comment]
好的 谢谢！
