### ISSUE TITLE
Is there a way to extract the stroke list in data array?

### ISSUE THREAD

**Issue by hulululuh** [sjtuplayer/Compositional_Neural_Painter#11]
Hello, I would like to replicate the stroke information (x0, y0, w, h, theta) created in your project in the game engine, but I am having difficulty extracting this information.
Is there a way to extract a list of strokes written based on normalized coordinates[0...1] instead of sub-space?

thanks in advance.

**Comment by sjtuplayer** [comment]
Hi~ You can refer to final_decode dunction in compositor
/test.py where we transform the local coordinates to global ones.

**Comment by sjtuplayer** [comment]
> Hello, I would like to replicate the stroke information (x0, y0, w, h, theta) created in your project in the game engine, but I am having difficulty extracting this information. Is there a way to extract a list of strokes written based on normalized coordinates[0...1] instead of sub-space?
> 
> thanks in advance.

Hi~ You can refer to final_decode function in compositor/test.py where we transform the local coordinates to global ones.

**Comment by hulululuh** [comment]
```
def final_decode():
 ...           
 global_bbox = (float(x01+x11*w0), float(y01+y11*h0), float(x01+x12*w0), float(y01+y12*h0))
 foregrounds, alphas = oil_decoder(x[:, :param_num + 3], True, global_bbox)

def oil_decoder(x, extract_stroke, bbox="", size=512):
    if extract_stroke:
        param = x[:, :param_num]
        stroke_color = x[:, -3:].view(-1, 1, 1, 3)
        param_list = torch.split(param, 1, dim=1)
        x0, y0, w, h, theta = [item.squeeze(-1) for item in param_list[:5]]
        t = theta

        lx = bbox[2] - bbox[0]
        ly = bbox[3] - bbox[1]

        for i in range(5):
            color = stroke_color[i][0][0].tolist()
            colors.append(color)
            global_px = bbox[0] + lx * (x0[i].item())
            global_py = bbox[1] + ly * (y0[i].item())
            global_sx = w[i].item()
            global_sy = h[i].item()
            strokes.append([global_px, global_py, global_sx, global_sy, t[i].item()])
```
I'm relatively new to AI models (specifically PyTorch) and image processing. I'm trying to understand how [x0, y0, w, h, theta] are used in the context of hierarchical bounding boxes, specifically in the local space (e.g., boxes0[0].boxes1[0]). Below is my approach so far:

1. In the final_decode function, calculate the bbox in global_space.
2. pass the bbox to oil_decoder(custom)
3. convert the local transform to global and save it for render.

and here are the results 
<img width="1047" alt="debug" src="https://github.com/sjtuplayer/Compositional_Neural_Painter/assets/5396978/52d1e4b7-65f3-407e-9fae-875714743b27">

1. i managed to fit a rotation correctly.
2. global_px and global_py kind of works first several strokes,but after this the positioning doesn't seem to be correct.(due to wrong bbox?)
3. Since the bouding box is made of a rectangle, the scale and rotation are expected to be distorted. Is there a solution to this?

**Comment by sjtuplayer** [comment]
> ```
> def final_decode():
>  ...           
>  global_bbox = (float(x01+x11*w0), float(y01+y11*h0), float(x01+x12*w0), float(y01+y12*h0))
>  foregrounds, alphas = oil_decoder(x[:, :param_num + 3], True, global_bbox)
> 
> def oil_decoder(x, extract_stroke, bbox="", size=512):
>     if extract_stroke:
>         param = x[:, :param_num]
>         stroke_color = x[:, -3:].view(-1, 1, 1, 3)
>         param_list = torch.split(param, 1, dim=1)
>         x0, y0, w, h, theta = [item.squeeze(-1) for item in param_list[:5]]
>         t = theta
> 
>         lx = bbox[2] - bbox[0]
>         ly = bbox[3] - bbox[1]
> 
>         for i in range(5):
>             color = stroke_color[i][0][0].tolist()
>             colors.append(color)
>             global_px = bbox[0] + lx * (x0[i].item())
>             global_py = bbox[1] + ly * (y0[i].item())
>             global_sx = w[i].item()
>             global_sy = h[i].item()
>             strokes.append([global_px, global_py, global_sx, global_sy, t[i].item()])
> ```
> 
> I'm relatively new to AI models (specifically PyTorch) and image processing. I'm trying to understand how [x0, y0, w, h, theta] are used in the context of hierarchical bounding boxes, specifically in the local space (e.g., boxes0[0].boxes1[0]). Below is my approach so far:
> 
> 1. In the final_decode function, calculate the bbox in global_space.
> 2. pass the bbox to oil_decoder(custom)
> 3. convert the local transform to global and save it for render.
> 
> and here are the results <img alt="debug" width="1047" src="https://private-user-images.githubusercontent.com/5396978/311222586-52d1e4b7-65f3-407e-9fae-875714743b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTM0MTMsIm5iZiI6MTcxMDI1MzExMywicGF0aCI6Ii81Mzk2OTc4LzMxMTIyMjU4Ni01MmQxZTRiNy02NWYzLTQwN2UtOWZhZS04NzU3MTQ3NDNiMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTQxODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcxZDA3OTU2YzAwOGEyNTRhM2JlMzRkYjc4ODdlNGEzNWQ5NGYxMDYwNWNhZTRkYjZhNmRkYmIxMTJhMzlkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7LXt-fReWdkDllVX5oQNfcmhr6Y4HP8Agu5RRlAXfyM">
> 
> 1. i managed to fit a rotation correctly.
> 2. global_px and global_py kind of works first several strokes,but after this the positioning doesn't seem to be correct.(due to wrong bbox?)
> 3. Since the bouding box is made of a rectangle, the scale and rotation are expected to be distorted. Is there a solution to this?

Seems that you need to change the width and length in the params.

**Comment by hulululuh** [comment]
I've got it worked! Thank you for your help.
