### ISSUE TITLE
Inquiry Regarding License Policy

### ISSUE THREAD

**Issue by hulululuh** [sjtuplayer/Compositional_Neural_Painter#12]
Hi @sjtuplayer, I'm interested in using your project and want to ensure I follow your licensing terms. Could you please clarify which license applies to your project? Any additional guidelines on how to comply would also be helpful. Thanks for your support and for making your project available to the community!

**Comment by sjtuplayer** [comment]
> Hi @sjtuplayer, I'm interested in using your project and want to ensure I follow your licensing terms. Could you please clarify which license applies to your project? Any additional guidelines on how to comply would also be helpful. Thanks for your support and for making your project available to the community!

Hi, we apply MIT License for our project.

**Comment by hulululuh** [comment]
Thanks for picking the MIT license! Super helpful for all of us wanting to use your work. 🙌
