### ISSUE TITLE
Which imagenet subset is used?

### ISSUE THREAD

**Issue by mritunjoyh** [sjtuplayer/Compositional_Neural_Painter#15]
I am very much interested in your research. Can you please tell me about your dataset subset? Have you used the full 1.3 TB data or the subset that is available in kaggle?

**Comment by sjtuplayer** [comment]
> I am very much interested in your research. Can you please tell me about your dataset subset? Have you used the full 1.3 TB data or the subset that is available in kaggle?

For Celeba-HQ, we use the full dataset, which contains around 20-30K images. And for ImageNet, We use the corresponding validation set, which contains around 60K images.

**Comment by mritunjoyh** [comment]
For training right?

**Comment by sjtuplayer** [comment]
Yes, you can randomly pick up 1000 images from them for evaluation.

**Comment by mritunjoyh** [comment]
Thanks a lot. Closing the issue.
