### ISSUE TITLE
Hello, the stroke renderer training code provided does not include the thinplatespline module?

### ISSUE THREAD

**Issue by xiaolu7521** [sjtuplayer/Compositional_Neural_Painter#2]
Hello, the stroke renderer training code provided does not include the thinplatespline module?

**Comment by sjtuplayer** [comment]
Hello, you can just remove thinplatespline, since its not used in the code. Or you can also choose to install it following: https://github.com/davegreenwood/torch-tps

**Comment by xiaolu7521** [comment]
Thank you for your response. I am very interested in this research topic, but due to hardware limitations, when will the pre-trained model be released? I would like to achieve good results as soon as possible in generating images.
