### ISSUE TITLE
Regarding the testing issue.

### ISSUE THREAD

**Issue by xiaolu7521** [sjtuplayer/Compositional_Neural_Painter#3]
Thank you for your response. I am very interested in this research topic, but due to hardware limitations, when will the pre-trained model be released? I would like to achieve good results as soon as possible in generating images.

**Comment by sjtuplayer** [comment]
Thanks for your attention to our work. I will release the checkpoints and testing code this weekend.  But since I'm quite bussy before CVPR and I have not prepared them so well, there may be some problem when you run it. So, if you encounter any problem, please feel free to contact me.

**Comment by Haoo906** [comment]
Thank you for your response. I'm very pleased to seek guidance from you on the test code you've released!

**Comment by xiaolu7521** [comment]
Thank you for your response. I'm very pleased to seek guidance from you on the test code you've released!

**Comment by sjtuplayer** [comment]
Hi!~The models have been uploaded and the test code has been updated.
