### ISSUE TITLE
关于训练数据集的问题

### ISSUE THREAD

**Issue by jzhangCSER01** [sjtuplayer/Compositional_Neural_Painter#4]
你好！请问你们在训练时用的 CelebA 数据集是 CelebA-HQ 吗？为什么 github 上给的数据集链接是低分辨率的 CelebA。谢谢

**Comment by sjtuplayer** [comment]
你好~！我们的模型在训练时使用的分辨率是128，因此用celeba和celeba-hq都是可以的，测试时我们才需要使用高分辨率的CelebA-HQ，因此给出的celeba数据集可以直接用于训练的

**Comment by jzhangCSER01** [comment]
好的，谢谢!
