### ISSUE TITLE
关于 compositor 中 test.py 代码中 decode 的疑问？

### ISSUE THREAD

**Issue by jzhangCSER01** [sjtuplayer/Compositional_Neural_Painter#5]
你好，我在 test.py 代码中看到 decode() 函数和 final_decode() 两个不同的函数，请问这两个具体有什么区别。它们在测试中得到的 MSE loss 并不相同。

**Comment by sjtuplayer** [comment]
decode使用的是训练好的可微渲染网络渲染得到的结果，纹理会比较弱，因此我们在得到所有的笔触参数后，会用基于仿射变换的渲染方法再次渲染，可以得到油画纹理较好的结果，但是会牺牲部分精度(也就是final_decode)，论文中我们统一使用的是final_decode的结果进行重建效果的比较

**Comment by jzhangCSER01** [comment]
> decode使用的是训练好的可微渲染网络渲染得到的结果，纹理会比较弱，因此我们在得到所有的笔触参数后，会用基于仿射变换的渲染方法再次渲染，可以得到油画纹理较好的结果，但是会牺牲部分精度(也就是final_decode)，论文中我们统一使用的是final_decode的结果进行重建效果的比较

但是我对 CelebA 图片进行测试，decode 得到的结果 MSE loss 比 final_decode 要小，这是正常的吗？

**Comment by sjtuplayer** [comment]
> 但是我对 CelebA 图片进行测试，decode 得到的结果 MSE loss 比 final_decode 要小，这是正常的吗？

是的， final_decode的重建精度会更差，但是相较于decode的没有纹理的结果，这应该才是Stroke-based rendering这个任务需要的结果

**Comment by jzhangCSER01** [comment]
> > 但是我对 CelebA 图片进行测试，decode 得到的结果 MSE loss 比 final_decode 要小，这是正常的吗？
> 
> 是的， final_decode的重建精度会更差，但是相较于decode的没有纹理的结果，这应该才是Stroke-based rendering这个任务需要的结果

谢谢，明白了
