### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Donkdot** [sjtuplayer/Compositional_Neural_Painter#6]
您好！很棒的工作，内容很有新意，论文中的图片也都很吸引眼球，想问一下您文章中绘图用的是什么软件呢，感觉效果很好，期待您的回复！

**Comment by sjtuplayer** [comment]
您好！感谢您的关注，我们论文中的所有图片都是直接使用powerpoint制作的

**Comment by Donkdot** [comment]
谢谢您！
