### ISSUE TITLE
关于对比实验的问题

### ISSUE THREAD

**Issue by luckyychen** [sjtuplayer/Compositional_Neural_Painter#7]
你好，请问你们在对比实验中与paint transformer做对比的时候是怎么更改绘画笔画数的？paint transformer的笔画数是训练网络的时候固定的，如果更改笔画数需要重新训练他的网络吗？

**Comment by sjtuplayer** [comment]
Paint Transformer的笔画数量可以通过分层的层数进行大致的控制，因此，在对比实验中，我们通过控制分层层数来控制笔画数量，但是因为无法准确设置笔触数量，因此为了实验的可靠性，我们几乎保证了Paint Transformer的笔画数量略大于对应的固定笔画数，以此说明我们模型的有效性
